language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.5
  - 1.6
  - nightly

notifications:
  email: false

script:
  - julia --project --check-bounds=yes -e 'import Pkg; Pkg.build("OREnvironment"); Pkg.test("OREnvironment"; coverage=true)'

# After successful build submit coverage report and deploy updated documentation
# But limit deployment to the linux worker so this is done only once.
after_success:
  # Install required packages for documentation
  - julia --project -e 'import Pkg; Pkg.add("Documenter"); Pkg.add("DocumenterTools");'
  - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
  - julia --project=docs/ docs/make.jl

  # Submit test coverage report
  - julia -e 'using Pkg; cd(Pkg.dir("OREnvironment")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
