language: julia

os:
  - linux
  - osx
  - windows

julia:
  - 1.3
  - 1.4
  - 1.5
  - nightly

notifications:
  email: false

codecov: true

script:
  - julia --project --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test("OREnvironment"; coverage=true)'

# After successful build submit coverage report and deploy updated documentation
# But limit deployment to the linux worker so this is done only once.
after_success:
  # Install required packages for coverage and documentation
  - julia --project -e 'import Pkg; Pkg.add("Coverage");'
  - julia --project -e 'import Pkg; Pkg.add("Documenter"); Pkg.add("DocumenterTools");'

  # Submit test coverage report
  - julia --project -e 'using Coverage; Codecov.submit(Coveralls.process_folder())'

  # Build and deploy documentation
  # - julia --project ./docs/make.jl
